### ISSUE TITLE
Couldn't download Arcadia

### ISSUE THREAD

**Issue by pgundlupetvenkatesh** [angal/arcadia#59]
I am looking for an windows installer of Arcadia. As I navigate to http://arcadia.rubyforge.org > Download menu I get an error message "RubyForge Could Not Connect to Database:"

**Comment by angal** [comment]
Hi,
http://arcadia.rubyforge.org is deprecated. The new site is http://www.arcadia-ide.org
You can install arcadia as gem.

Regards
Antonio

**Comment by pgundlupetvenkatesh** [comment]
Ok, thank you @Antonio.
Could you please redirect the users from the old download page to the new one since the old site is kept alive. just as an end-user suggestion.
Appreciate your help thanks again.

**Comment by angal** [comment]
Unfortunately I can not have more access to the site rubyforge.org
