### ISSUE TITLE
Change font and theme

### ISSUE THREAD

**Issue by krthr** [angal/arcadia#62]
Hey! I love Arcadia. Its light - like vim or gedit <3

But... i have a question, can i change the theme and font? Thank you!

**Comment by angal** [comment]
Hi, 
arcadia has a basic system of themes.
You can define it by creating a configuration file under the arcadia/conf directory.
The convention for file name is theme-<name>.conf
For example, the default theme is dark and you can see a theme-dark.conf file.
To change the theme, you can set to ~/.arcadia.conf "theme" property.
If you create your theme for example from the theme-dark.conf
In it you can overwrite any property you see commented in ~/.arcadia.conf.
For example, if you add
Edit.font = Verdana 14
overwrite the editor font.
The same thing can be done on the icons in the theme-<name>.res.rb file
If you need more details, I'm here.
Thanks for support
